### ISSUE TITLE
MacOS build and run examples failed

### ISSUE THREAD

**Issue by xbwee1024** [MegEngine/MegFlow#15]
## error log | 日志或报错信息
cargo run --example run_with_plugins -- -p logical_test
   Compiling unicode-segmentation v1.8.0
   Compiling unicode-width v0.1.8
   Compiling vec_map v0.8.2
   Compiling os_str_bytes v2.4.0
   Compiling strsim v0.10.0
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling textwrap v0.12.1
   Compiling heck v0.3.3
   Compiling clap_derive v3.0.0-beta.2
   Compiling clap v3.0.0-beta.2
   Compiling flow-rs v0.1.0 (/Users/weixiaobin/Repos/github/MegFlow/flow-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 16.46s
     Running `/Users/xxx/Repos/github/MegFlow/target/debug/examples/run_with_plugins -p logical_test`
thread 'main' panicked at 'module megflow not found: PyErr { type: <class 'ModuleNotFoundError'>, value: ModuleNotFoundError("No module named 'megflow'"), traceback: None }', flow-rs/src/loader/python/mod.rs:139:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    15835 abort      cargo run --example run_with_plugins -- -p logical_test
## context | 编译/运行环境
MacOS Big Sur
11.5.2 (20G95)
master 00de1fff1315e1c17ff23988905a36ddc3a8a222
python 3.8.10

## how to reproduce | 复现步骤
1. brew install rust
2. cd MegFlow; cargo build; cd flow-python; python setup.py install
3. cd examples; cargo run --example run_with_plugins -- -p logical_test

**Comment by Easonzero** [comment]
@xbwee1024 您好，
我尝试在我自己的mac上复现，结果没复现。
烦请做如下自检辅助定位：
1. `otool -L /Users/weixiaobin/Repos/github/MegFlow/target/debug/examples/run_with_plugins`,
    - 查看下`run_with_plugins`链接的`libpython{}.dylib`是哪个版本, 是否与`python --version`得到的版本一致
2. `python -c "import megflow"`是否能够执行成功

**Comment by tpoisonooo** [comment]
"'module megflow not found"， 文档里的  python3 setup.py install --user 执行了嘛？

**Comment by tpoisonooo** [comment]
报错的意思是   import  megflow 失败，我们排查方向就是  python 环境不对、 安装时 python setup.py install 不对这种。FYI。
