### ISSUE TITLE
Documentations of built-in applications are not available. 

### ISSUE THREAD

**Issue by kennymckormick** [MegEngine/MegFlow#35]
RT

**Comment by tpoisonooo** [comment]
方便给一下链接明示嘛？

**Comment by kennymckormick** [comment]
Hi, tpoisonooo, 

This link in your documentation is invalid: https://megflow.readthedocs.io/zh_CN/flow-python/examples/cat_finder/README. 
The link is shown here: 
![image](https://user-images.githubusercontent.com/34324155/139587324-94c1a1f9-5521-40ed-989d-a9fd5dc237cd.png)

Users can not get familiar with this project without documentation 😄.

**Comment by tpoisonooo** [comment]
[read the docs](https://megflow.readthedocs.io/zh_CN/latest/built-in-applications/cat_finder.html) has been updated,  pls use chrome/firefox  private mode to check it.

The [code](https://github.com/megengine/megflow/tree/fix-readthedocs) would be merged later.
