### ISSUE TITLE
MegFlow 后续可以支持在win平台运行吗？

### ISSUE THREAD

**Issue by Qianlu5110** [MegEngine/MegFlow#37]
## platform | 软硬件环境
win 10 i5-10210U MX330

## error log | 日志或报错信息
ERROR: megflow-0.1.0-py37-none-linux_x86_64.whl is not a supported wheel on this platform.

**Comment by tpoisonooo** [comment]
之前未规划此内容。近期开发计划：

https://github.com/MegEngine/MegFlow/projects/1

我理解 win 编译应该不会特别难（Rust 最初承诺的就是支持 win），欢迎 PR。

**Comment by tpoisonooo** [comment]
我猜测你其实是要这个：build-on-win10 ?    https://github.com/MegEngine/MegFlow/blob/master/docs/how-to-build-and-run/build-on-win10.zh.md

**Comment by Qianlu5110** [comment]
收到，多谢
