### ISSUE TITLE
如何在MegFLow的框架下利用Flask等框架传输纯文本数据？

### ISSUE THREAD

**Issue by wanghan0501** [MegEngine/MegFlow#40]
## detail | 详细描述
目前看官方的教程，只有ImageServer和VideoServer，两者必须要传输Image或者Video数据，虽然有extra_data能够解析URL，但是无法只传输纯文本信息。

希望官方教程增加在MegFlow框架下，利用Flask等Web框架作为source的示例代码，方便自定义传输数据的类型

**Comment by tpoisonooo** [comment]
提供另一个备选方案在 https://github.com/MegEngine/MegFlow/tree/template04-generator  

* generator 可以拉数据、然后交给 pipeline 
* generator 不能等别人推数据过来

原因是：  Flask 的 App.route 注册的 callback 函数无法唤醒  MegFlow Node  。 
前者属于第三方线程，后者属于异步任务。


其他比较短期的方案：
* MegFlow ImageServer 输入的图片、extra 字段都不再强制。里面发现没给图就不解码。由调用方保证参数都给全了

**Comment by wanghan0501** [comment]
1. 如果不限于Flask框架，在Python的体系内有可能实现这个需求?
2. 关于短期方案，如果官方能支持最好了
3. 是建议官方加一个textserver，用于处理纯文本数据
4. 或者支持application/json格式

**Comment by tpoisonooo** [comment]
打算这么实现短期方案：

提供一个 BytesServer，传任意想要的东西， String 也好语音的 .pcm 也好。

用法示例见： https://github.com/MegEngine/MegFlow/tree/template05-bytes

```bash
    [[graphs.nodes]]
    name = "source"
    ty = "BytesServer"
    port = 8080
```

用 POST 请求提交 bytes
```Python
import requests

def test():
    ip = 'localhost'
    port = '8080'
    url = f'http://{ip}:{port}/analyze/bytes'
    data = b'abcde'

    headers = {'Content-Length': f'{len(data)}', 'Content-Type': '*/*'}
    res = requests.post(url, data=data, headers=headers)
    print(res.content)


if __name__ == "__main__":
    test()
```

里面的结点收到的是个  numpy.ndarray，也不关心具体是个啥。
https://github.com/MegEngine/MegFlow/blob/1cc507674d92dda3936402e4619259ffaa00f459/det.py#L27

**Comment by tpoisonooo** [comment]
短期方案开发中。

**Comment by tpoisonooo** [comment]
BTW, `loguru` 卡住的问题需要个复现环境，目前不能复现。
