### ISSUE TITLE
计算图在未完全初始化的情况下接收到客户端请求，会直接阻塞

### ISSUE THREAD

**Issue by wanghan0501** [MegEngine/MegFlow#42]
## detail | 详细描述
在整个计算图还没完全启动的时候，发请求，图会阻塞。想请教下，MegFlow怎么判断计算图是否完全启动了？如果没有能否未来添加判断整个计算图完全启动的状态函数。

**Comment by tpoisonooo** [comment]
感觉是建图过程中没有增加保护状态。我来复现一下。

**Comment by tpoisonooo** [comment]
已沟通，调用方因为 http 太慢/需要传图，自己写的 UDP，用 TCP 没事。

本质诉求还是  #40
